apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sreplicalimits
  annotations:
    metadata.gatekeeper.sh/title: "Replica Limits"
    description: >-
      Requires that objects with the field `spec.replicas` (Deployments,
      ReplicaSets, etc.) specify a number of replicas within defined ranges.
spec:
  crd:
    spec:
      names:
        kind: K8sReplicaLimits
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          type: object
          properties:
            min_replicas:
              type: integer
            max_replicas:
              type: integer
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sreplicalimits
        deployment_name = input.review.object.metadata.name
        violation[{"msg": msg}] {
            spec := input.review.object.spec
            not input_replica_min_limit(spec)
            msg := sprintf("MIN: %v. Allowed ranges: %v", [deployment_name, input.parameters.min_replicas,input.parameters.min_replicas])
        }
        input_replica_min_limit(spec) {
            provided := input.review.object.spec.replicas
            min_rpl := input.parameters.min_replicas
            min_rpl <= provided
        }
